theme:
  - nig-theme
  - osuny-plugin-centered-header
  - osuny-plugin-centered-layout
_merge: deep
params:
  logo:
    header: '/assets/images/logo.png'
    footer: '/assets/images/logo-full.png'
  menu:
    primary:
      level_2:
        summary:
          active: true
          source: "Summary" # "Summary" | "meta_description"
          truncate: false