theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.png'
    footer: '/assets/images/logo-full.png'
  home:
    head:
      title: site